# Generated by Django 4.1.2 on 2023-05-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excelfile',
            old_name='keyword',
            new_name='month',
        ),
        migrations.AlterField(
            model_name='excelfile',
            name='file',
            field=models.FileField(unique=True, upload_to='uploads/'),
        ),
    ]
