# Generated by Django 4.1.2 on 2023-05-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_manager', '0002_rename_keyword_excelfile_month_alter_excelfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfile',
            name='month',
            field=models.DateField(),
        ),
    ]
