# Generated by Django 4.1.2 on 2023-05-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_manager', '0003_alter_excelfile_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfile',
            name='filename',
            field=models.CharField(blank=True, default='nofilename', max_length=50),
        ),
    ]
