# Generated by Django 4.1.2 on 2023-05-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_manager', '0004_excelfile_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfile',
            name='project_name',
            field=models.CharField(default='noprojectname', max_length=100),
        ),
    ]
